---
- name: Run nginx container
  docker_container:
    name: nginx-proxy
    image: amnonbn/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config_files/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    network_mode: bridge
    links:
      - kibana:kibana

