---
- name: Run elasticsearch container
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    volumes:
      - ./config_files/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    network_mode: bridge

- name: Wait until elasticsearch is up and running
  wait_for: timeout=30

